<script>
    $(document).ready(function(){
        $("#strB").click(function(){
            $("#str").show();
            $('#strB').addClass('active');
            $("#sikp").hide();
            $('#sikpB').removeClass('active');
            $("#spk").hide();
            $('#spkB').removeClass('active');
            $("#rkk").hide();
            $('#rkkB').removeClass('active');
        });
        $("#sikpB").click(function(){
            $("#str").hide();
            $('#strB').removeClass('active');
            $("#sikp").show();
            $('#sikpB').addClass('active');
            $("#spk").hide();
            $('#spkB').removeClass('active');
            $("#rkk").hide();
            $('#rkkB').removeClass('active');
        });
        $("#spkB").click(function(){
            $("#str").hide();
            $('#strB').removeClass('active');
            $("#sikp").hide();
            $('#sikpB').removeClass('active');
            $("#spk").show();
            $('#spkB').addClass('active');
            $("#rkk").hide();
            $('#rkkB').removeClass('active');
        });
        $("#rkkB").click(function(){
            $("#str").hide();
            $('#strB').removeClass('active');
            $("#sikp").hide();
            $('#sikpB').removeClass('active');
            $("#spk").hide();
            $('#spkB').removeClass('active');
            $("#rkk").show();
            $('#rkkB').addClass('active');
        });
    });
</script>
