<script>
    $(document).ready(function(){
        $("#data_skpB").click(function(){
            $("#dataSkp").show();
            $('#data_skpB').addClass('active');
            $("#formSkp").hide();
            $('#form_skpB').removeClass('active');
            $("#pengukuran").hide();
            $('#pengukuranB').removeClass('active');
            $("#perilakuKerja").hide();
            $('#perilaku_kerjaB').removeClass('active');
            $("#penilaian").hide();
            $('#penilaianB').removeClass('active');
        });
        $("#form_skpB").click(function(){
            $("#dataSkp").hide();
            $('#data_skpB').removeClass('active');
            $("#formSkp").show();
            $('#form_skpB').addClass('active');
            $("#pengukuran").hide();
            $('#pengukuranB').removeClass('active');
            $("#perilakuKerja").hide();
            $('#perilaku_kerjaB').removeClass('active');
            $("#penilaian").hide();
            $('#penilaianB').removeClass('active');
        });
        $("#pengukuranB").click(function(){
            $("#dataSkp").hide();
            $('#data_skpB').removeClass('active');
            $("#formSkp").hide();
            $('#form_skpB').removeClass('active');
            $("#pengukuran").show();
            $('#pengukuranB').addClass('active');
            $("#perilakuKerja").hide();
            $('#perilaku_kerjaB').removeClass('active');
            $("#penilaian").hide();
            $('#penilaianB').removeClass('active');
        });
        $("#perilaku_kerjaB").click(function(){
            $("#dataSkp").hide();
            $('#data_skpB').removeClass('active');
            $("#formSkp").hide();
            $('#form_skpB').removeClass('active');
            $("#pengukuran").hide();
            $('#pengukuranB').removeClass('active');
            $("#perilakuKerja").show();
            $('#perilaku_kerjaB').addClass('active');
            $("#penilaian").hide();
            $('#penilaianB').removeClass('active');
        });
        $("#penilaianB").click(function(){
            $("#dataSkp").hide();
            $('#data_skpB').removeClass('active');
            $("#formSkp").hide();
            $('#form_skpB').removeClass('active');
            $("#pengukuran").hide();
            $('#pengukuranB').removeClass('active');
            $("#perilakuKerja").hide();
            $('#perilaku_kerjaB').removeClass('active');
            $("#penilaian").show();
            $('#penilaianB').addClass('active');
        });
    });
</script>
